- name: Program 7
  hosts: all
  tasks:	
    - name: Install Git
      yum: name=git state=installed
    - name: Install wget
      yum: name=wget state=installed
    - name: Ansible debug print.
      debug:
        msg: "Git and Wget Installed"
