---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: Install the httpd apps
    yum: name=httpd state=installed
  - name: start the httpd service
    service: name=httpd state=started
  - name: Template a file to /etc/files.conf
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
