---
- hosts: test
  tasks:
  - name: --------Install httpd------------
    yum:
      name: httpd
      state: latest
  - name: -----Enable httpd-------------
    service:
      name: httpd
      state: started

