---
- name: This installs and start webserver.Variale taken from command prompt 
  hosts: all
  vars_prompt:
    - name: "myname"
      prompt: "Please enter your name"
  tasks:
  - name: Install httpd package
    yum: name=httpd state=installed
  - name: start httpd service
    service: name=httpd state=started
  - name: Ansible debug print example.
    debug:
      msg: "this is test {{ myname }}"

