- name: This sets up an httpd webserver
  hosts: db
  tasks:
  - name: create a empty fle
    file: dest=/var/www/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - name: Ansible debug print example.
    debug:
      msg: "this is test"
