---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: Install the httpd apps
    yum: name=httpd state=installed
  - name: start the httpd service
    service: name=httpd state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
    notify:
      - Restart Apache
  - name: Ansible debug print example.
    debug:
      msg: "this is test {{ myname }}"

  handlers:
     - name: Restart Apache
       service: name=httpd state=restarted

