---
- name: This sets up an httpd webserver
  hosts: all
  vars_prompt:
    - name: "Version"
      prompt: "Which version Do you want to install?"
      private: no
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }} state=installed
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - name: Ansible debug print example.
    debug:
      msg: "{{ myname }}"
  - name: Ansible vars_prompt print example.
    debug:
      msg: "{{ Version }}"
  - name: include default step variables
    include_vars: var-ext.yaml
  - name: Ansible vars_prompt print example.
    debug:
      msg: "My age is only {{ age }}"
