---
- name: to crtae the index.tml file on /var/www/html location   
  hosts: all
  tasks:
    - name: going  to create the index.html file  
      file:  
        path: /var/www/html/index.html
        state: touch
    - name: copy the content
      copy:
       content: "Welcome to the Devops.com i!\n"
       dest: /var/www/html/index.html
        
