---
- name: to install apache ob QA and DEV env
  hosts: all
  tasks:
   - name: Install the httpd apps
     yum: name=httpd state=installed
   - name: start the httpd service
     service: name=httpd state=started
   - name: copy a file
     copy: dest=/var/www/html/ src="index.html"
      
