---
- name: setup a webserver(httpd) and use httpd as a variable decalared in inventory
  hosts: all
  tasks:
    - name: going  to install "{{ package }}" on server
      yum:
        name: "{{ package }}"
        state: present
    - name: starting the {{ service }} on server 
      service:
        name: "{{ service }}"
        state: started 
    - name: Ansible debug print example.
      debug:
        msg: "this is test {{ myname }}"
    - name: copy a file
      copy: 
        dest: /var/www/html/ 
        src: index.html
    - name: Template a file to /etc/files.conf
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
