---
- name: playbook and setup a webserver(httpd) and use httpd as a variable decalared in Playbooks.
  hosts: all
  vars:
   package: "httpd" 
   service: "httpd" 
  tasks:
    - name: going  to install {{ package }} on server
      yum:
        name: "{{ package }}"
        state: present
    - name: starting the {{ service }} on server 
      service:
        name: "{{ service }}"
        state: started
        enabled: true

     
