---
- name: This sets up an httpd webserver
  hosts: all
  vars:
    myname: "Ravi"
    package: "httpd"
    service: "httpd"
  tasks:
  - name: install the httpd apps
    yum: name={{ package }} state=installed
