---
# tasks file for role1
  - name: Install the httpd apps
    yum: pkg={{ item }} state=installed
    with_items:
      - git
      - httpd
      - ntp    
  - name: start the httpd service
    service: name=httpd state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
    notify:
      - Restart Apache
  - name: Ansible debug print example.
    debug:
      msg: "this is test {{ myname }}"
  - name: Run a script with arguments (using 'cmd' parameter)
    script:
      cmd: script.sh
    when: ansible_os_family == "Debian"
