---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: Install the httpd apps
    yum: name={{ pac }} state=installed
  - name: start the httpd service
    service: name={{ ser }} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - name: Ansible debug print example.
    debug:
      msg: "Varilabe in invetory has been succesfully tested"
