---
- name: This sets up an httpd webserver
  hosts: all
  vars:
    pac1: "httpd"
    ser1: "httpd"
  tasks:
  - name: Install the httpd apps
    yum: name={{ pac1 }} state=installed
  - name: start the httpd service
    service: name={{ ser1 }} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - name: Ansible debug print example.
    debug:
      msg: "Variable in playbook tested Successfully"
