---
- name: This sets up an httpd webserver
  hosts: all
  vars_prompt:
    - name: "Service"
      prompt: "Which service Do you want to install?"
      private: no
  tasks:
  - name: Install the httpd apps
    yum: name={{ Service }} state=installed
  - name: start the httpd service
    service: name={{ Service }} state=started
  - name: Ansible vars_prompt print example.
    debug:
      msg: "{{ Service }}"
  - name: Ansible vars_prompt print example.
    debug:
      msg: "The service {{ Service }} is installed"
