---
- name: This sets up an httpd webserver
  hosts: all
  vars:
    myname: "Radha"
    package: "httpd"
    service: "httpd"
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }} state=present
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: Ansible debug print example.
    debug:
      msg: "The service {{ service }} installed from playbook"
