---
- name: playbook and setup a webserver(httpd) and use httpd as a variable decalared in Playbooks.
  hosts: all
  vars_files:
    ext-var.yml
  tasks:
    - name: going  to install {{ package }} on server
      yum:
        name: "{{ package }}"
        state: present
    - name: staring {{ service }} on server
      service:
         name: "{{ service }}"
         state: started
         enabled: true


     
