---
- name: Assignment 1
  hosts: all
  tasks:
  - name: Install HTTPD
    yum: name=httpd state=installed
    when: (ansible_os_family == "Debian") or
          (ansible_os_family == "RedHat")
  - name: Start HTTPD
    service: name=httpd state=started
    when: (ansible_os_family == "Debian") or
          (ansible_os_family == "RedHat")
  - name: Create HTML File
    copy: dest=/var/www/html/ src="index.html"
    when: (ansible_os_family == "Debian") or
          (ansible_os_family == "RedHat")
  - name: Ansible debug print example.
    debug:
      msg: "Successful"
    when: (ansible_os_family == "Debian") or
          (ansible_os_family == "RedHat")
...
